# 指令前缀 若和别的游戏冲突，更换其他前缀即可
rulePrefix:
- "~"
- "～"
- "#?蓝原"
- "#?蓝色星原"

# 角色图片
imgMaxSize: 10 #上传图片大小限制 MB
imgPath:
#角色图片库的路径 从Bot根目录开始，如 'plugins/yoyo-image/' ，路径下须是以角色命名的文件夹
- plugins/yoyo-image
# todo
characterImgPath: [] #立绘图 无背景图片 
# todo
heroGuidePath: [] #角色攻略图
imgUpAuth: all # 图片上传权限 "master"|"admin"|"owner"|"all"
imgDelAuth: all # 图片删除权限 "master"|"admin"|"owner"|"all"
# 资源配置  
# 图标载入地址，  git 从 https://gitee.com/yoyo-plugin/yoyo-icon 载入   wiki  从bwiki载入
iconSource:
- wiki
- https://gitee.com/yoyo-plugin/yoyo-icon/raw/master/
# 监测PV播放量
PVList:
- BV1Jr421n7n4
- BV1KUopYZEs5
# 签到
sign: true # 开启签到
signWithdrawal: false # 签到撤回
signInclude: [] # 签到包含群聊
signExclude: [] # 签到排除群聊


# 进群欢迎
increaseInclude:
  - group_id: 123456
    text: 欢迎来到普罗米利亚！星临者！
increaseCd: 10 # 秒
# 表情包
emoticon: false
# 表情包服务器 (如果有自建服务器，请加上服务器地址)
emoticonServer:
  - https://h.winterqkl.cn
# AI
baseURL: '' # 模型地址
apiKey: '' # api-key
model: '' # 模型名称
imgModel: '' # 图片生成模型名称
msgCacheLength: 10 # 群组内历史聊天内容长度
MaxUsrMsgCount: 10 # 上下文对话保存数量
aiInclude: [] # AI触发的群聊
